version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  jq: circleci/jq@2.2.0

workflows:
  maven_test:
    jobs:
      - all

jobs:
  all:
    executor:
      name: maven/default
      tag: "11.0"
    steps:
      - jq/install
      - checkout
      - run:
          name: Make soy templates
          command: cd soy && make
      - run:
          name: Build jar
          command: ./mvnw package --update-snapshots
      - run:
          name: Publish to heroku
          command: sh ./heroku.sh
