version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  jq: circleci/jq@2.2.0

workflows:
  maven_test:
    jobs:
      - prebuild
      - maven/test:
          requires:
            - prebuild
          executor:
            name: maven/default
            tag: "11.0"
          maven_command: ./mvnw
          command: "package --update-snapshots"
      - postbuild:
          requires:
            - maven/test

jobs:
  prebuild:
    executor:
      name: maven/default
      tag: "11.0"
    steps:
      - checkout
      - run:
          name: Prebuild
          command: cd soy && make
  postbuild:
    executor:
      name: jq/default
    steps:
      - checkout
      - run:
          name: Postbuild
          command: sh heroku.sh
