version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  jq: circleci/jq@2.2.0

workflows:
  maven_test:
    jobs:
      - prebuild
      - maven/test:
          requires:
            - prebuild
          executor:
            name: maven/default
            tag: "11.0"
          maven_command: ./mvnw
          command: "package --update-snapshots"
      - postbuild:
          requires:
            - maven/test

jobs:
  prebuild:
    executor:
      name: maven/default
      tag: "11.0"
    steps:
      - checkout
      - run:
          name: Make soy templates
          command: cd soy && make
  postbuild:
    executor:
      name: maven/default
    steps:
      - jq/install
      - run:
          name: Publish to heroku
          command: ls -la && sh --help && sh ./heroku.sh
