version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  jq: circleci/jq@2.2.0

workflows:
  main:
    jobs:
      - all:
          filters:
            branches:
              only:
                - master
      - maven/test:
          executor:
            name: maven/default
            tag: "11.0"
          filters:
            branches:
              ignore:
                - master

jobs:
  all:
    executor:
      name: maven/default
      tag: "11.0"
    steps:
      - jq/install
      - checkout
      - run:
          name: Make soy templates
          command: cd soy && make
      - maven/with_cache:
          maven_command: ./mvnw
          steps:
            - run:
                name: Build jar
                command: ./mvnw package --update-snapshots
      - run:
          name: Publish to heroku
          command: sh heroku.sh
